# Generated by Django 2.2.28 on 2023-01-14 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('ENGINEERING', 'ENGINEERING'), ('MEDICAL', 'MEDICAL')], max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('phone', models.BigIntegerField(max_length=20)),
                ('profile_pic', models.ImageField(blank=True, default='/usericon.png/', null=True, upload_to='myimage')),
                ('college', models.CharField(max_length=50)),
                ('programe', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
