# Generated by Django 4.1.5 on 2023-01-14 18:46

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userpannel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpannel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
