# Generated by Django 4.1.5 on 2023-01-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userpannel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpannel',
            name='phone',
            field=models.BigIntegerField(max_length=20),
        ),
    ]
