# Generated by Django 4.1.5 on 2023-01-15 05:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userpannel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpannel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
